name: food_stock_app
description: A new Flutter project. #TODO add description

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^1.17.1
  # firebase_auth: ^3.3.19
  # firebase_auth_oauth: ^1.2.0
  firebase_analytics: ^9.1.9
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17

  auto_route: ^4.0.1
  freezed_annotation: ^2.0.3
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  flutter_speed_dial: ^6.0.0
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  flutter_slidable: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.0.3+1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
